import time
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys

def edit_field(driver, field_name, input):
    action = ActionChains(driver)
    action.double_click(field_name)
    action.perform()
    edit_field = driver.find_element_by_class_name('grid-input-cell')
    edit_field.clear()
    edit_field.send_keys(input)
    time.sleep(2)
    edit_field.send_keys(Keys.TAB)
    time.sleep(2)

def test_setup_charges_changes(driver):
    driver.switch_to.window(driver.window_handles[0])
    driver.implicitly_wait(2)
    select_charges_setup=driver.find_element_by_css_selector('div.actions.tools-setup > button:nth-child(9)')
    select_charges_setup.click()
    driver.implicitly_wait(5)
    driver.switch_to.window(driver.window_handles[1])
    driver.implicitly_wait(5)
    select_add_charges=driver.find_element_by_css_selector('i.add.square.icon')
    select_add_charges.click()
    driver.implicitly_wait(5)
    add_charge_name=driver.find_element_by_css_selector('div > div.top-form > div.row.first > div > div > input')
    add_charge_name.clear()
    driver.implicitly_wait(10)
    add_charge_name.send_keys('My Charge1 ')
    driver.implicitly_wait(10)
    add_charge_name.send_keys(Keys.TAB)
    driver.implicitly_wait(10)
    select_charge_type=driver.find_element_by_css_selector('#flat_fee > span')
    select_charge_type.click()
    driver.implicitly_wait(10)
    enter_charge_amount=driver.find_element_by_css_selector('div > div.top-form > div.row.second > div.charge-value > div.form-field.text > div > input')
    enter_charge_amount.send_keys('2021')
    driver.implicitly_wait(8)
    enter_charge_amount.send_keys(Keys.TAB)
    driver.implicitly_wait(8)
    # select_base=driver.find_element_by_css_selector('#R\$GLV3WgyM')
    # select_base.click()
    select_base = driver.find_element_by_css_selector('div.visible.menu.transition > :nth-child(2)')
    select_base.click()
    driver.implicitly_wait(15)

    add_account_no=driver.find_element_by_css_selector('div > div.top-form > div.row.second > div.form-field.text.account > div > input')
    add_account_no.send_keys('1500')
    driver.implicitly_wait(10)
    display_percentage=driver.find_element_by_css_selector('div > div.form-field.checkbox.display-percent > div')
    display_percentage.click()
    driver.implicitly_wait(8)
    display_excluded_amt=driver.find_element_by_css_selector('div > div.form-field.checkbox.display-flat > div')
    display_excluded_amt.click()
    driver.implicitly_wait(8)

def test_exclude_details(driver):
    select_add_exclude_amount=driver.find_element_by_css_selector('div.tools-actions > div > a:nth-child(1) > i')
    select_add_exclude_amount.click()
    driver.implicitly_wait(10)
    add_name=driver.find_element_by_css_selector('input.grid-input-cell')
    add_name.click()
    add_name.send_keys('X1')
    driver.implicitly_wait(10)
    add_name.send_keys(Keys.TAB)
    add_desc=driver.find_element_by_css_selector('div.cell.body.text.desc.editable.field-range.field-range-top.field-range-right.field-range-bottom.field-range-left.field-range-pivot.read-only > span')
    action = ActionChains(driver)
    action.double_click(add_desc)
    action.perform()
    add_desc1=driver.find_element_by_css_selector('input.grid-input-cell')
    add_desc1.send_keys("Amount to be excluded")
    driver.implicitly_wait(10)
    add_desc1.send_keys(Keys.TAB)
    add_total=driver.find_element_by_css_selector('div.cell.body.number.total.editable.field-range.field-range-top.field-range-right.field-range-bottom.field-range-left.field-range-pivot.read-only > span')
    action = ActionChains(driver)
    action.double_click(add_total)
    action.perform()
    add_total1=driver.find_element_by_css_selector('input.grid-input-cell')
    add_total1.send_keys('100')
    driver.implicitly_wait(10)
    add_total1.send_keys(Keys.ENTER)
    driver.implicitly_wait(15)

    delete_row=driver.find_element_by_css_selector('div.tools-actions > div > a:nth-child(2) > i')
    delete_row.click()
    driver.implicitly_wait(20)
    select_exclude_group_drpdown=driver.find_element_by_css_selector('div.exclude-groups-container > div > i')
    select_exclude_group_drpdown.click()
    driver.implicitly_wait(20)
    select_group=driver.find_element_by_css_selector('div.exclude-groups-container > div > div > div:nth-child(1)')
    select_group.click()
    driver.implicitly_wait(15)
    Apply_charge=driver.find_element_by_css_selector('div.top-form > div.row.first > button')
    Apply_charge.click()
    time.sleep(2)

    # close_setup = driver.find_element_by_css_selector('.ui.small.primary.button')
    # close_setup.click()
    # driver.implicitly_wait(5)
    driver.switch_to.window(driver.window_handles[0])
    time.sleep(2)

    topsheet_check_charge=driver.find_element_by_css_selector('div:nth-child(47) > div.cell.body.index.non-editable.read-only')
    action = ActionChains(driver)
    action.double_click(topsheet_check_charge)
    action.perform()
    time.sleep(2)

def test_delete_charges(driver):
    driver.switch_to.window(driver.window_handles[1])
    select_applied_charge=driver.find_element_by_css_selector('div.item.applied.active')
    select_applied_charge.click()
    driver.implicitly_wait(10)
    delete_charges=driver.find_element_by_css_selector('div.action-buttons.no-select > a:nth-child(2) > i')
    delete_charges.click()
    time.sleep(2)
    close_setup = driver.find_element_by_css_selector('.ui.small.primary.button')
    close_setup.click()








