import time
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys

def edit_field(driver, field_name, input):
    action = ActionChains(driver)
    action.double_click(field_name)
    action.perform()
    edit_field = driver.find_element_by_class_name('grid-input-cell')
    edit_field.clear()
    edit_field.send_keys(input)
    time.sleep(2)
    edit_field.send_keys(Keys.TAB)
    time.sleep(2)

def test_setup_credits_changes(driver):
    driver.switch_to.window(driver.window_handles[0])
    driver.implicitly_wait(2)
    select_credits_setup=driver.find_element_by_css_selector('div.actions.tools-setup > button:nth-child(8)')
    select_credits_setup.click()
    driver.implicitly_wait(5)
    driver.switch_to.window(driver.window_handles[1])
    driver.implicitly_wait(5)
    select_add_credits=driver.find_element_by_css_selector('i.add.square.icon')
    select_add_credits.click()
    driver.implicitly_wait(5)
    add_credit_name=driver.find_element_by_css_selector('div > div.top-form > div.row.first > div > div > input')
    add_credit_name.clear()
    driver.implicitly_wait(10)
    add_credit_name.send_keys('Credit Item 1')
    driver.implicitly_wait(10)
    add_credit_name.send_keys(Keys.TAB)
    driver.implicitly_wait(10)
    applied_cred_amount=driver.find_element_by_css_selector('div.form-field.text.credit_cap > div > input')
    applied_cred_amount.send_keys('100')
    driver.implicitly_wait(8)
    applied_cred_amount.send_keys(Keys.TAB)
    driver.implicitly_wait(8)
    enter_discount=driver.find_element_by_css_selector('div.form-field.text.discount > div > input')
    enter_discount.send_keys('5')
    driver.implicitly_wait(8)

    add_account_no = driver.find_element_by_css_selector('div.form-field.text.account > div > input')
    add_account_no.send_keys('1500')
    driver.implicitly_wait(10)

def test_add_row_details(driver):
    select_add_row=driver.find_element_by_css_selector('div.tools-actions > div > a:nth-child(1) > i')
    select_add_row.click()
    driver.implicitly_wait(10)
    add_name=driver.find_element_by_css_selector('input.grid-input-cell')
    add_name.click()
    add_name.send_keys('Y1')
    driver.implicitly_wait(10)
    add_name.send_keys(Keys.TAB)
    add_desc=driver.find_element_by_css_selector('div.cell.body.text.desc.editable.field-range.field-range-top.field-range-right.field-range-bottom.field-range-left.field-range-pivot.read-only > span')
    action = ActionChains(driver)
    action.double_click(add_desc)
    action.perform()
    add_desc1=driver.find_element_by_css_selector('input.grid-input-cell')
    add_desc1.send_keys('Amount to be credited')
    driver.implicitly_wait(10)
    add_desc1.send_keys(Keys.TAB)
    gross_total=driver.find_element_by_css_selector('div.cell.body.number.gross_total.editable.field-range.field-range-top.field-range-right.field-range-bottom.field-range-left.field-range-pivot.read-only > span')
    action = ActionChains(driver)
    action.double_click(gross_total)
    action.perform()
    add_gross_total = driver.find_element_by_css_selector('input.grid-input-cell')
    add_gross_total.send_keys('100')
    driver.implicitly_wait(10)
    add_gross_total.send_keys(Keys.TAB)
    cap_type=driver.find_element_by_css_selector('div.list-container > span > i')
    cap_type.click()
    driver.implicitly_wait(10)
    select_cap_type=driver.find_element_by_css_selector('#qs')
    select_cap_type.click()
    driver.implicitly_wait(15)

    add_cap = driver.find_element_by_css_selector('div.splitter-pane.right > div > div.grid > div.grid-body.alt > div > div.cell.body.number.cap.editable.read-only')
    add_cap.click()
    driver.implicitly_wait(10)
    action = ActionChains(driver)
    action.double_click(add_cap)
    action.perform()
    add_cap1 = driver.find_element_by_css_selector('input.grid-input-cell')
    add_cap1.send_keys('10')
    driver.implicitly_wait(10)
    add_cap1.send_keys(Keys.TAB)
    add_per = driver.find_element_by_css_selector('div.cell.body.number.rate.editable.field-range.field-range-top.field-range-right.field-range-bottom.field-range-left.field-range-pivot.read-only')
    action = ActionChains(driver)
    action.double_click(add_per)
    action.perform()
    add_per1 = driver.find_element_by_css_selector('input.grid-input-cell')
    add_per1.send_keys('2')
    driver.implicitly_wait(10)
    add_per1.send_keys(Keys.ENTER)

    driver.implicitly_wait(15)

    delete_row = driver.find_element_by_css_selector('div.tools-actions > div > a:nth-child(2) > i')
    delete_row.click()
    driver.implicitly_wait(20)

    select_include_group_drpdown = driver.find_element_by_css_selector('div.group-menu.no-select > div > i')
    select_include_group_drpdown.click()
    driver.implicitly_wait(20)
    select_group = driver.find_element_by_css_selector('div.group-menu.no-select > div > div > div:nth-child(1)')
    select_group.click()
    driver.implicitly_wait(15)

    select_exclude_fringes_drpdown=driver.find_element_by_css_selector('div.fringe-menu.no-select > div > i')
    select_exclude_fringes_drpdown.click()
    driver.implicitly_wait(20)
    select_fringe=driver.find_element_by_css_selector('div.fringe-menu.no-select > div > div > div:nth-child(2) > div > label')
    select_fringe.click()
    driver.implicitly_wait(20)

    Apply_credit = driver.find_element_by_css_selector('div.top-form > div.row.first > button')
    Apply_credit.click()
    time.sleep(2)

    # close_setup = driver.find_element_by_css_selector('.ui.small.primary.button')
    # close_setup.click()
    # driver.implicitly_wait(5)
    driver.switch_to.window(driver.window_handles[0])
    time.sleep(2)
    verify_credit=driver.find_element_by_css_selector('div:nth-child(50) > div.cell.body.text.description.non-editable.read-only')
    assert 'Credit Item 1' in verify_credit.text
    time.sleep(2)

    topsheet_check_credits = driver.find_element_by_css_selector('div:nth-child(50) > div.cell.body.index.non-editable.read-only')
    action = ActionChains(driver)
    action.double_click(topsheet_check_credits)
    action.perform()
    time.sleep(2)

def test_delete_credits(driver):
    driver.switch_to.window(driver.window_handles[1])
    select_applied_credits = driver.find_element_by_css_selector('div.item.applied.active')
    select_applied_credits.click()
    driver.implicitly_wait(10)
    delete_credits = driver.find_element_by_css_selector('div.action-buttons.no-select > a:nth-child(2) > i')
    delete_credits.click()
    time.sleep(2)
    close_setup = driver.find_element_by_css_selector('.ui.small.primary.button')
    close_setup.click()