import time
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys

def edit_field(driver, field_name, input):
    action = ActionChains(driver)
    action.double_click(field_name)
    action.perform()
    edit_field = driver.find_element_by_class_name('grid-input-cell')
    edit_field.clear()
    edit_field.send_keys(input)
    time.sleep(2)
    edit_field.send_keys(Keys.TAB)
    time.sleep(2)

def test_subBudget(driver):
    driver.switch_to.window(driver.window_handles[0])
    driver.implicitly_wait(2)
    select_ellipsis_icon= driver.find_element_by_css_selector('a > div.ui.top.left.pointing.dropdown.ellipsis-menu > i')
    select_ellipsis_icon.click()
    time.sleep(2)
    select_subBudget_option=driver.find_element_by_css_selector('div.ui.active.visible.top.left.pointing.dropdown.ellipsis-menu > div > div:nth-child(4)')
    select_subBudget_option.click()
    time.sleep(2)
    driver.switch_to.window(driver.window_handles[1])
    time.sleep(3)

    search_budget=driver.find_element_by_css_selector('div > div.content-picker-pane.source > div.content-picker-search > div > input[type=text]')
    search_budget.click()
    search_budget.send_keys('1300')
    driver.implicitly_wait(20)
    uncheck_budget=driver.find_element_by_css_selector('div.content-picker-pane.source > div.content-picker-content > ul > li > ul > li:nth-child(3) > div')
    uncheck_budget.click()
    driver.implicitly_wait(20)
    select_exclude_dropdown=driver.find_element_by_css_selector('div.content-picker-content > ul > li > span.suppress-trigger > i')
    select_exclude_dropdown.click()
    driver.implicitly_wait(20)
    select_empty_detail_accounts=driver.find_element_by_css_selector('div.ui.bottom.right.popup.transition.visible.suppress > div:nth-child(1) > label')
    select_empty_detail_accounts.click()
    driver.implicitly_wait(10)
    select_zero_total_amount= driver.find_element_by_css_selector('div.ui.bottom.right.popup.transition.visible.suppress > div:nth-child(2) > label')
    select_zero_total_amount.click()
    time.sleep(2)
    select_exclude_dropdown.click()
    click_next_button=driver.find_element_by_css_selector('div.status-bar > div > button.ui.small.button.secondary')
    click_next_button.click()
    time.sleep(2)

#Applied tools and Included Lines:
    select_remove_detail_line=driver.find_element_by_css_selector('div.active-pane > div > div.remove-lines > div > i')
    select_remove_detail_line.click()
    driver.implicitly_wait(20)
    select_option1=driver.find_element_by_css_selector('div.remove-lines > div > div.visible.menu.transition > div:nth-child(2)')
    select_option1.click()
    time.sleep(2)
    select_fringes_header=driver.find_element_by_css_selector('div.tabs-container > div.ui.attached.tabular.menu > a:nth-child(2)')
    select_fringes_header.click()
    driver.implicitly_wait(20)
    uncheck_fringe1=driver.find_element_by_css_selector('div.tools-tab-contents > div.grid-container > div > div.grid-body.alt > div:nth-child(1) > div.cell.body.checkbox.check.non-editable.read-only > div > div > div')
    uncheck_fringe1.click()
    time.sleep(2)
    select_groups_header=driver.find_element_by_css_selector('div.tabs-container > div.ui.attached.tabular.menu > a:nth-child(3)')
    select_groups_header.click()
    driver.implicitly_wait(20)
    uncheck_group1=driver.find_element_by_css_selector('div.grid-body.alt > div:nth-child(2) > div.cell.body.checkbox.check.non-editable.read-only > div')
    uncheck_group1.click()
    driver.implicitly_wait(10)
    select_group_label1=driver.find_element_by_css_selector('div.tools-bar > div.groups-options > div:nth-child(1) > label')
    select_group_label1.click()
    select_group_label2=driver.find_element_by_css_selector('div.tools-bar > div.groups-options > div:nth-child(2) > label')
    select_group_label2.click()
    time.sleep(2)
    select_currency=driver.find_element_by_css_selector('div.tabs-container > div.ui.attached.tabular.menu > a:nth-child(4)')
    select_currency.click()
    driver.implicitly_wait(20)

    select_sets_header = driver.find_element_by_css_selector('div.tabs-container > div.ui.attached.tabular.menu > a:nth-child(5)')
    select_sets_header.click()
    driver.implicitly_wait(20)
    find_set = driver.find_element_by_css_selector('div.tools-tab-contents > div.tools-bar > div > div > input[type=text]')
    find_set.click()
    find_set.send_keys('7514')
    time.sleep(2)
    unselect_set = driver.find_element_by_css_selector('div.grid-container > div > div.grid-body.alt > div > div.cell.body.checkbox.check.non-editable.read-only > div > div')
    unselect_set.click()
    time.sleep(3)

    select_credits_header = driver.find_element_by_css_selector('div.tabs-container > div.ui.attached.tabular.menu > a:nth-child(6)')
    select_credits_header.click()
    driver.implicitly_wait(20)
    uncheck_credit1 = driver.find_element_by_css_selector('div.tools-tab-contents > div.grid-container > div > div.grid-body.alt > div:nth-child(1) > div.cell.body.checkbox.check.non-editable.read-only > div > div > div')
    uncheck_credit1.click()
    time.sleep(2)
    select_charges_header = driver.find_element_by_css_selector('div.tabs-container > div.ui.attached.tabular.menu > a:nth-child(7)')
    select_charges_header.click()
    time.sleep(2)

    create_budget=driver.find_element_by_css_selector('div > button.ui.small.button.primary')
    create_budget.click()
    time.sleep(3)
    driver.switch_to.window(driver.window_handles[1])
    select_open_budget=driver.find_element_by_css_selector('div.status-bar > button.ui.small.button.primary')
    select_open_budget.click()
    time.sleep(2)

    driver.switch_to.window(driver.window_handles[0])
    select_ellipsis_icon = driver.find_element_by_css_selector('div.ui.top.left.pointing.dropdown.ellipsis-menu > i')
    select_ellipsis_icon.click()
    driver.implicitly_wait(10)
    select_close_budget = driver.find_element_by_css_selector('div.ui.active.visible.top.left.pointing.dropdown.'
                                                              'ellipsis-menu > div > div:nth-child(2) > span')
    select_close_budget.click()
    driver.implicitly_wait(10)


